# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('sexo', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=8)),
            ],
        ),
    ]
