# Generated by Django 2.0.5 on 2019-07-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '__first__'),
        ('estudiante', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notafinal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprobado', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia')),
            ],
        ),
    ]
