# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('cuerpo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('leido', models.BooleanField()),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Administrador')),
                ('reseptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.Padre')),
            ],
        ),
    ]
