# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('cuerpo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('dias', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('publicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Administrador')),
            ],
        ),
    ]
