# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=2)),
                ('ciclo', models.CharField(max_length=1)),
            ],
        ),
    ]
