# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('profesor', '0001_initial'),
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examen2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examen3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notaMes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.Mes')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor')),
            ],
        ),
    ]
