# Generated by Django 2.0.5 on 2019-07-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
